### ISSUE TITLE
Kodi doesn't show up in Youtube app cast devices list

### ISSUE THREAD

**Issue by ju-sti** [enen92/script.tubecast#14]
Installed tubecast 1.0.7
SSDP in tubecast settings is enabled
Using Youtube App Version 13.45.52 on Android
The problem is: Kodi doesn't show up as cast device in the youtube app.
Tubecast/Casting works fine when I pair the device with the code (however it's not nice to use because of issue #12 )

Excerpts from the logfile (192.168.1.15 is my smartphone)

```
18:01:20.886 T:2522870528   DEBUG: [script.tubecast] script.tubecast: Datagram received. Address:('192.168.1.15', 39507); Content:M-SEARCH * HTTP/1.1
                                            HOST: 239.255.255.250:1900
                                            MAN: "ssdp:discover"
                                            MX: 1
                                            ST: urn:dial-multiscreen-org:service:dial:1
18:01:20.888 T:2522870528   DEBUG: [script.tubecast] script.tubecast: Answering datagram
18:01:20.934 T:2514481920   DEBUG: [script.tubecast] script.tubecast: 192.168.1.15 - - "GET /ssdp/device-desc.xml HTTP/1.1" 200 990
18:01:21.189 T:2514481920   DEBUG: [script.tubecast] script.tubecast: Datagram received. Address:('192.168.1.15', 39507); Content:M-SEARCH * HTTP/1.1
                                            HOST: 239.255.255.250:1900
                                            MAN: "ssdp:discover"
                                            MX: 1
                                            ST: urn:dial-multiscreen-org:service:dial:1
18:01:21.194 T:2514481920   DEBUG: [script.tubecast] script.tubecast: Answering datagram
18:01:21.505 T:2514481920   DEBUG: [script.tubecast] script.tubecast: Datagram received. Address:('192.168.1.15', 39507); Content:M-SEARCH * HTTP/1.1
                                            HOST: 239.255.255.250:1900
                                            MAN: "ssdp:discover"
                                            MX: 1
                                            ST: urn:dial-multiscreen-org:service:dial:1
18:01:21.507 T:2514481920   DEBUG: [script.tubecast] script.tubecast: Answering datagram
```

Later there are logged python exceptions directly after the youtube requesting the device-desc.xml.

```
19:50:21.597 T:2562802432   DEBUG: [script.tubecast] script.tubecast: 192.168.1.15 - - "GET /ssdp/device-desc.xml HTTP/1.1" 500 59
19:50:21.599 T:2562802432   DEBUG: ----------------------------------------
19:50:21.600 T:2562802432   DEBUG: Exception happened during processing of request from
19:50:21.600 T:2562802432   DEBUG: ('192.168.1.15', 42416)
19:50:21.605 T:2562802432   ERROR: Traceback (most recent call last):
19:50:21.606 T:2562802432   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 596, in process_request_thread
19:50:21.606 T:2562802432   ERROR:     self.finish_request(request, client_address)
19:50:21.607 T:2562802432   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
19:50:21.607 T:2562802432   ERROR:     self.RequestHandlerClass(request, client_address, self)
19:50:21.608 T:2562802432   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
19:50:21.608 T:2562802432   ERROR:     self.finish()
19:50:21.609 T:2562802432   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
19:50:21.609 T:2562802432   ERROR:     self.wfile.close()
19:50:21.610 T:2562802432   ERROR:   File "/usr/lib/python2.7/socket.py", line 283, in close
19:50:21.611 T:2562802432   ERROR:     self.flush()
19:50:21.612 T:2562802432   ERROR:   File "/usr/lib/python2.7/socket.py", line 307, in flush
19:50:21.612 T:2562802432   ERROR:     self._sock.sendall(view[write_offset:write_offset+buffer_size])
19:50:21.619 T:2562802432   ERROR: error: [Errno 32] Broken pipe
19:50:21.619 T:2562802432   DEBUG: ----------------------------------------
```

When opening http://kodi-ip:8008/ssdp/device-desc.xml with firefox everything looks ok:

```
<?xml version="1.0" encoding="utf-8"?>
    <root xmlns="urn:schemas-upnp-org:device-1-0" xmlns:r="urn:restful-tv-org:schemas:upnp-dd">
        <specVersion>
        <major>1</major>
        <minor>0</minor>
        </specVersion>
        <URLBase>http://192.168.1.117:8008</URLBase>
        <device>
            <deviceType>urn:schemas-upnp-org:device:dail:1</deviceType>
            <friendlyName>osmc</friendlyName>
            <manufacturer>Google Inc.</manufacturer>
            <modelName>Eureka Dongle</modelName>
            <UDN>uuid:68467cc7-dfaf-59f7-8d34-532befbd69e5</UDN>
            <serviceList>
                <service>
                    <serviceType>urn:schemas-upnp-org:service:dail:1</serviceType>
                    <serviceId>urn:upnp-org:serviceId:dail</serviceId>
                    <controlURL>/ssdp/notfound</controlURL>
                    <eventSubURL>/ssdp/notfound</eventSubURL>
                    <SCPDURL>/ssdp/notfound</SCPDURL>
                </service>
            </serviceList>
        </device>
    </root>
```

**Comment by enen92** [comment]
It is hard to debug this without reproducing. Where are you running kodi/tubecast? My guess would be the firewall blocking the SSDP datagrams

**Comment by ju-sti** [comment]
Kodi is running on a Raspberry, connected by wifi. I have run SSDP discovery on my pc (connected to the same wifi): tubecast and my hisense tv are both replying so I don't think there is a firewall interfering.
```
M-SEARCH * HTTP/1.1
HOST: 239.255.255.250:1900
MAN: "ssdp:discover"
ST: urn:dial-multiscreen-org:service:dial:1
MX: 3


HTTP/1.1 200 OK
LOCATION: http://192.168.1.117:8008/ssdp/device-desc.xml
CACHE-CONTROL: max-age=1800
CONFIGID.UPNP.ORG: 7337
BOOTID.UPNP.ORG: 7337
USN: uuid:68467cc7-dfaf-59f7-8d34-532befbd69e5
ST: urn:dial-multiscreen-org:service:dial:1



HTTP/1.1 200 OK
LOCATION: http://192.168.1.77:56790/dd.xml
CACHE-CONTROL: max-age=1800
EXT:
BOOTID.UPNP.ORG: 1
SERVER: Linux/2.6 UPnP/1.1 quick_ssdp/1.1
ST: urn:dial-multiscreen-org:service:dial:1
USN: uuid:b08889b3-62d9-cf03-9533-7b69f8cf5e07::urn:dial-multiscreen-org:service:dial:1
WAKEUP:MAC=C8:3D:D4:BA:BB:90;Timeout=60
```

**Comment by enen92** [comment]
@ju-sti glad you solved the issue. In the forums a user reported `socket.getfqdn(host)` as being the culprit for a similar issue: https://forum.kodi.tv/showthread.php?tid=329153&pid=2793202#pid2793202

**Comment by pannal** [comment]
I've tried all fixes mentioned here, to no avail. Tubecast worked the first couple of months that I've had my Vero 4K (OSMC). Might this actually be a platform issue?
