### ISSUE TITLE
'module' object has no attribute 'fromfd'

### ISSUE THREAD

**Issue by loggin** [enen92/script.tubecast#41]
Managed to set this up and get it working yesterday but today I am getting the following:

	2020-03-29 15:58:01.024 T:5352   ERROR: Exception in thread Player:
	Traceback (most recent call last):
	File "C:\Program Files (x86)\Kodi\system\python\Lib\threading.py", line 801, in __bootstrap_inner
	self.run()
	File "C:\Program Files (x86)\Kodi\system\python\Lib\threading.py", line 754, in run
	self.__target(*self.__args, **self.__kwargs)
	File "C:\Users\Mark\AppData\Roaming\Kodi\addons\script.tubecast\resources\lib\tubecast\youtube\app.py", line 470, in __player_thread
	self.listener.force_stop()
	File "C:\Users\Mark\AppData\Roaming\Kodi\addons\script.tubecast\resources\lib\tubecast\youtube\app.py", line 530, in force_stop
	sock = socket.fromfd(self.r.raw.fileno(), socket.AF_INET, socket.SOCK_STREAM)
	AttributeError: 'module' object has no attribute 'fromfd'

**Comment by siku2** [comment]
It looks like `socket.fromfd` is only available on UNIX systems in Python 2 (see the [documentation](https://docs.python.org/2/library/socket.html#socket.fromfd)).
The [patch that ported this function to Windows](https://bugs.python.org/issue1378) apparently never made it's way to version 2.x.

I think the only way to avoid this issue is to avoid calling it for Python 2 on Windows. But this could then lead to other problems...

Did this cause the add-on to stop working entirely, @loggin?

**Comment by enen92** [comment]
@siku2 I think this is only used to avoid the hang on shutdown (kill the requests socket), maybe we should be safe just trying/except there

**Comment by siku2** [comment]
@enen92 it's also called when the [listener is replaced](https://github.com/enen92/script.tubecast/blob/master/resources/lib/tubecast/youtube/app.py#L148) which happens when pairing while a client is already connected or even when the current client disconnects.
I think it's probably a good idea to handle the exception.

**Comment by loggin** [comment]
> It looks like `socket.fromfd` is only available on UNIX systems in Python 2 (see the [documentation](https://docs.python.org/2/library/socket.html#socket.fromfd)).
> The [patch that ported this function to Windows](https://bugs.python.org/issue1378) apparently never made its way to version 2.x.
> 
> I think the only way to avoid this issue is to avoid calling it for Python 2 on Windows. But this could then lead to other problems...
> 
> Did this cause the add-on to stop working entirely, @loggin?

Hi sorry for not getting back sooner, obvs reasons right now. Basically my phone can't find the kodi service. Rebooting the PC does solve the issue though but it does intermittently happen, restarting Kodi itself doesn't do anything to resolve the issue in the short term
